# This is a basic workflow to help you get started with Actions

name: Omoolen Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: Decode KAKAO_LOGIN_API
      env:
        NAVER_MAP_CLIENT_ID: ${{ secrets.KAKAO_LOGIN_API }}
      run: echo kakao.login.key=\"$KAKAO_LOGIN_API\" > ./local.properties
          
    - name: Gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Change gradlew permissions
      run: chmod +x ./gradlew

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
       
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace
     
     
    - run: './gradlew assembleRelease'
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNELS }}
        file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
        file_name: 'Omoolen.apk'
        file_type: 'apk'
        initial_comment: '${{ github.ref }} Success Deploy Capin Release APK'
        
    - name: upload apk artifact 
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: action-slack
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
        author_name: Notify Build
        fields: repo,message,commit,author
        custom_payload: |
          { 
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
            }]
          }
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
